---
#Jobqueue Configuration
jobqueue:

    #The control service configuration
    control:
        class:  "NineThousand\Jobqueue\Service\JobqueueControl"

    #Job component configuration
    job:
        class:  "NineThousand\Jobqueue\Job\StandardJob"

    #adapter configuration includes job adapter and job controll mapping
    adapter:
        class:  "NineThousand\Jobqueue\Vendor\Doctrine\Adapter\Queue\DoctrineQueueAdapter"
        options:
            job_entity_class:       "NineThousand\Bundle\NineThousandJobqueueBundle\Entity\Job"
            job_adapter_class:      "NineThousand\Bundle\NineThousandJobqueueBundle\Vendor\Doctrine\Adapter\Job\DoctrineJobAdapter"
            history_entity_class:   "NineThousand\Bundle\NineThousandJobqueueBundle\Entity\History"
            history_adapter_class:  "NineThousand\Jobqueue\Vendor\Doctrine\Adapter\History\DoctrineHistoryAdapter"
            log_adapter_class:      "NineThousand\Jobqueue\Vendor\Doctrine\Adapter\Log\MonologAdapter"
            jobcontrol:
                type_mapping:
                    SymfonyConsoleJobControl:   "NineThousand\Jobqueue\Vendor\Symfony2\Adapter\Job\Control\Symfony2ConsoleJobControl"
    
    #ui configuration
    ui:
        options:
            pagnation:
                limit: 20

---
#CodeMemeDaemonBundle Configuration Example
code_meme_daemon:
    daemons:
        #creates a daemon using default options
        jobqueue: ~
